[server]
headless = true
port = $PORT
enableCORS = false

[theme]
primaryColor = "#005792"
backgroundColor = "#f7f9fb"
secondaryBackgroundColor = "#e1ecf4"
textColor = "#262730"
font = "Varela Round"
